### ISSUE TITLE
Gogs starting before mysql

### ISSUE THREAD

**Issue by meyerbro** [geerlingguy/ansible-role-gogs#15]
Hi, first thanks for the great work!

I'm creating this "issue" because I saw you have this

templates/gogs.unit.j2:#After=mysqld.service

but it doesn't uncomment when gogs_use_mysql: true...

How can I do that? This is making gogs not come back when the box is rebooted.

Thanks,
Felipe

**Comment by meyerbro** [comment]
In fact, the only thing that will work with the mysql ansible role (geerlingguy one) is this:
After=mariadb.service

**Comment by meyerbro** [comment]
```
tasks:
    - name: gogs should start after mysql
      replace:
        path: /etc/systemd/system/gogs.service
        regexp: '#After=mysqld.service'
        replace: 'After=mariadb.service'
```
