### ISSUE TITLE
Make Gogs work out of the box on RHEL/CentOS 7

### ISSUE THREAD

**Issue by geerlingguy** [geerlingguy/ansible-role-gogs#4]
The init script included with Gogs seems to not want to work with RHEL/CentOS 7. See: https://travis-ci.org/geerlingguy/ansible-role-gogs/jobs/109519333#L858

```
TASK: [role_under_test | Ensure Gogs is running.] ***************************** 
failed: [localhost] => {"failed": true}
msg: Failed to start gogs.service: Unit gogs.service failed to load: No such file or directory.
```

I even tried explicitly restarting the systemctl daemon but that didn't seem to help (I had the following code inside `init-setup.yml`):

``` yaml
# SEE: https://github.com/ansible/ansible-modules-core/issues/191
- name: Restart systemctl daemon on systemd systems.
  shell: systemctl daemon-reload
  when: gogs_file_symlinks.changed and (ansible_os_family == "RedHat" and ansible_distribution_major_version|int == 7)
```
